"""Remove tenant_id

Revision ID: c73b5aa6ffd4
Revises: f7304259f1a9
Create Date: 2026-06-30 20:58:05.514003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c73b5aa6ffd4'
down_revision: Union[str, Sequence[str], None] = 'f7304259f1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Moved drop_table('tenants') to the end
    op.drop_index(op.f('ix_accrual_logs_tenant_id'), table_name='accrual_logs')
    op.drop_constraint(op.f('fk_accrual_logs_tenant'), 'accrual_logs', type_='foreignkey')
    op.drop_column('accrual_logs', 'tenant_id')
    op.drop_index(op.f('ix_approval_chains_tenant_id'), table_name='approval_chains')
    op.drop_constraint(op.f('fk_approval_chains_tenant'), 'approval_chains', type_='foreignkey')
    op.drop_column('approval_chains', 'tenant_id')
    op.drop_index(op.f('ix_approval_steps_tenant_id'), table_name='approval_steps')
    op.drop_constraint(op.f('fk_approval_steps_tenant'), 'approval_steps', type_='foreignkey')
    op.drop_column('approval_steps', 'tenant_id')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_constraint(op.f('fk_audit_logs_tenant'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'tenant_id')
    op.drop_index(op.f('ix_calendar_integrations_tenant_id'), table_name='calendar_integrations')
    op.drop_constraint(op.f('fk_calendar_integrations_tenant'), 'calendar_integrations', type_='foreignkey')
    op.drop_column('calendar_integrations', 'tenant_id')
    op.drop_index(op.f('ix_contact_messages_tenant_id'), table_name='contact_messages')
    op.drop_constraint(op.f('fk_contact_messages_tenant'), 'contact_messages', type_='foreignkey')
    op.drop_column('contact_messages', 'tenant_id')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_constraint(op.f('fk_departments_tenant'), 'departments', type_='foreignkey')
    op.drop_column('departments', 'tenant_id')
    op.drop_index(op.f('ix_employee_images_tenant_id'), table_name='employee_images')
    op.drop_constraint(op.f('fk_employee_images_tenant'), 'employee_images', type_='foreignkey')
    op.drop_column('employee_images', 'tenant_id')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_constraint(op.f('fk_employees_tenant'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'tenant_id')
    op.drop_index(op.f('ix_leave_approvals_tenant_id'), table_name='leave_approvals')
    op.drop_constraint(op.f('fk_leave_approvals_tenant'), 'leave_approvals', type_='foreignkey')
    op.drop_column('leave_approvals', 'tenant_id')
    op.drop_index(op.f('ix_leave_balances_tenant_id'), table_name='leave_balances')
    op.drop_constraint(op.f('fk_leave_balances_tenant'), 'leave_balances', type_='foreignkey')
    op.drop_column('leave_balances', 'tenant_id')
    op.drop_index(op.f('ix_leave_policies_tenant_id'), table_name='leave_policies')
    op.drop_constraint(op.f('fk_leave_policies_tenant'), 'leave_policies', type_='foreignkey')
    op.drop_column('leave_policies', 'tenant_id')
    op.drop_index(op.f('ix_leave_requests_tenant_id'), table_name='leave_requests')
    op.drop_constraint(op.f('fk_leave_requests_tenant'), 'leave_requests', type_='foreignkey')
    op.drop_column('leave_requests', 'tenant_id')
    op.drop_index(op.f('ix_leave_types_tenant_id'), table_name='leave_types')
    op.drop_constraint(op.f('fk_leave_types_tenant'), 'leave_types', type_='foreignkey')
    op.drop_column('leave_types', 'tenant_id')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_constraint(op.f('fk_notifications_tenant'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'tenant_id')
    op.drop_index(op.f('ix_onboarding_applications_tenant_id'), table_name='onboarding_applications')
    op.drop_constraint(op.f('fk_onboarding_applications_tenant'), 'onboarding_applications', type_='foreignkey')
    op.drop_column('onboarding_applications', 'tenant_id')
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.drop_constraint(op.f('fk_organizations_tenant'), 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'tenant_id')
    op.drop_index(op.f('ix_platform_config_tenant_id'), table_name='platform_config')
    op.drop_constraint(op.f('fk_platform_config_tenant'), 'platform_config', type_='foreignkey')
    op.drop_column('platform_config', 'tenant_id')
    op.drop_index(op.f('ix_platform_owners_tenant_id'), table_name='platform_owners')
    op.drop_constraint(op.f('fk_platform_owners_tenant'), 'platform_owners', type_='foreignkey')
    op.drop_column('platform_owners', 'tenant_id')
    op.drop_index(op.f('ix_public_holidays_tenant_id'), table_name='public_holidays')
    op.drop_constraint(op.f('fk_public_holidays_tenant'), 'public_holidays', type_='foreignkey')
    op.drop_column('public_holidays', 'tenant_id')
    op.drop_index(op.f('ix_role_permissions_tenant_id'), table_name='role_permissions')
    op.drop_constraint(op.f('fk_role_permissions_tenant'), 'role_permissions', type_='foreignkey')
    op.drop_column('role_permissions', 'tenant_id')
    op.drop_index(op.f('ix_system_settings_tenant_id'), table_name='system_settings')
    op.drop_constraint(op.f('fk_system_settings_tenant'), 'system_settings', type_='foreignkey')
    op.drop_column('system_settings', 'tenant_id')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('plan_type', sa.VARCHAR(length=20), server_default=sa.text("'starter'::character varying"), autoincrement=False, nullable=False),
    sa.Column('module_access', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('max_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('access_days', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey'))
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.add_column('system_settings', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_system_settings_tenant'), 'system_settings', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_system_settings_tenant_id'), 'system_settings', ['tenant_id'], unique=False)
    op.add_column('role_permissions', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_role_permissions_tenant'), 'role_permissions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_role_permissions_tenant_id'), 'role_permissions', ['tenant_id'], unique=False)
    op.add_column('public_holidays', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_public_holidays_tenant'), 'public_holidays', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_public_holidays_tenant_id'), 'public_holidays', ['tenant_id'], unique=False)
    op.add_column('platform_owners', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_platform_owners_tenant'), 'platform_owners', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_platform_owners_tenant_id'), 'platform_owners', ['tenant_id'], unique=False)
    op.add_column('platform_config', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_platform_config_tenant'), 'platform_config', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_platform_config_tenant_id'), 'platform_config', ['tenant_id'], unique=False)
    op.add_column('organizations', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_organizations_tenant'), 'organizations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.add_column('onboarding_applications', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_onboarding_applications_tenant'), 'onboarding_applications', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_onboarding_applications_tenant_id'), 'onboarding_applications', ['tenant_id'], unique=False)
    op.add_column('notifications', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_notifications_tenant'), 'notifications', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.add_column('leave_types', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_leave_types_tenant'), 'leave_types', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_leave_types_tenant_id'), 'leave_types', ['tenant_id'], unique=False)
    op.add_column('leave_requests', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_leave_requests_tenant'), 'leave_requests', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_leave_requests_tenant_id'), 'leave_requests', ['tenant_id'], unique=False)
    op.add_column('leave_policies', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_leave_policies_tenant'), 'leave_policies', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_leave_policies_tenant_id'), 'leave_policies', ['tenant_id'], unique=False)
    op.add_column('leave_balances', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_leave_balances_tenant'), 'leave_balances', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_leave_balances_tenant_id'), 'leave_balances', ['tenant_id'], unique=False)
    op.add_column('leave_approvals', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_leave_approvals_tenant'), 'leave_approvals', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_leave_approvals_tenant_id'), 'leave_approvals', ['tenant_id'], unique=False)
    op.add_column('employees', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_employees_tenant'), 'employees', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.add_column('employee_images', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_employee_images_tenant'), 'employee_images', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_employee_images_tenant_id'), 'employee_images', ['tenant_id'], unique=False)
    op.add_column('departments', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_departments_tenant'), 'departments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.add_column('contact_messages', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_contact_messages_tenant'), 'contact_messages', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_contact_messages_tenant_id'), 'contact_messages', ['tenant_id'], unique=False)
    op.add_column('calendar_integrations', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_calendar_integrations_tenant'), 'calendar_integrations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_calendar_integrations_tenant_id'), 'calendar_integrations', ['tenant_id'], unique=False)
    op.add_column('audit_logs', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_audit_logs_tenant'), 'audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.add_column('approval_steps', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_approval_steps_tenant'), 'approval_steps', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_approval_steps_tenant_id'), 'approval_steps', ['tenant_id'], unique=False)
    op.add_column('approval_chains', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_approval_chains_tenant'), 'approval_chains', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_approval_chains_tenant_id'), 'approval_chains', ['tenant_id'], unique=False)
    op.add_column('accrual_logs', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_accrual_logs_tenant'), 'accrual_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_accrual_logs_tenant_id'), 'accrual_logs', ['tenant_id'], unique=False)
    # Moved create_table to the top
    # ### end Alembic commands ###
