"""initial migration

Revision ID: f7304259f1a9
Revises: 
Create Date: 2026-06-30 15:42:58.363777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7304259f1a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.alter_column('accrual_logs', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_accrual_logs_tenant_id'), 'accrual_logs', ['tenant_id'], unique=False)
    op.alter_column('approval_chains', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_approval_chains_tenant_id'), 'approval_chains', ['tenant_id'], unique=False)
    op.alter_column('approval_steps', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_approval_steps_tenant_id'), 'approval_steps', ['tenant_id'], unique=False)
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.alter_column('calendar_integrations', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_calendar_integrations_tenant_id'), 'calendar_integrations', ['tenant_id'], unique=False)
    op.alter_column('contact_messages', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_contact_messages_tenant_id'), 'contact_messages', ['tenant_id'], unique=False)
    op.alter_column('departments', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.alter_column('employee_images', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_employee_images_tenant_id'), 'employee_images', ['tenant_id'], unique=False)
    op.alter_column('employees', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.alter_column('leave_approvals', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_leave_approvals_tenant_id'), 'leave_approvals', ['tenant_id'], unique=False)
    op.alter_column('leave_balances', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_leave_balances_tenant_id'), 'leave_balances', ['tenant_id'], unique=False)
    op.alter_column('leave_policies', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_leave_policies_tenant_id'), 'leave_policies', ['tenant_id'], unique=False)
    op.alter_column('leave_requests', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_leave_requests_tenant_id'), 'leave_requests', ['tenant_id'], unique=False)
    op.alter_column('leave_types', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_leave_types_tenant_id'), 'leave_types', ['tenant_id'], unique=False)
    op.alter_column('notifications', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.alter_column('onboarding_applications', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_onboarding_applications_admin_email'), table_name='onboarding_applications')
    op.create_index(op.f('ix_onboarding_applications_super_admin_email'), 'onboarding_applications', ['super_admin_email'], unique=False)
    op.create_index(op.f('ix_onboarding_applications_tenant_id'), 'onboarding_applications', ['tenant_id'], unique=False)
    op.alter_column('organizations', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.alter_column('platform_config', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_platform_config_tenant_id'), 'platform_config', ['tenant_id'], unique=False)
    op.alter_column('platform_owners', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_platform_owners_tenant_id'), 'platform_owners', ['tenant_id'], unique=False)
    op.alter_column('public_holidays', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_public_holidays_tenant_id'), 'public_holidays', ['tenant_id'], unique=False)
    op.alter_column('role_permissions', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_role_permissions_tenant_id'), 'role_permissions', ['tenant_id'], unique=False)
    op.alter_column('system_settings', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_system_settings_tenant_id'), 'system_settings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_system_settings_tenant_id'), table_name='system_settings')
    op.alter_column('system_settings', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_role_permissions_tenant_id'), table_name='role_permissions')
    op.alter_column('role_permissions', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_public_holidays_tenant_id'), table_name='public_holidays')
    op.alter_column('public_holidays', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_platform_owners_tenant_id'), table_name='platform_owners')
    op.alter_column('platform_owners', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_platform_config_tenant_id'), table_name='platform_config')
    op.alter_column('platform_config', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.alter_column('organizations', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_onboarding_applications_tenant_id'), table_name='onboarding_applications')
    op.drop_index(op.f('ix_onboarding_applications_super_admin_email'), table_name='onboarding_applications')
    op.create_index(op.f('ix_onboarding_applications_admin_email'), 'onboarding_applications', ['super_admin_email'], unique=False)
    op.alter_column('onboarding_applications', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.alter_column('notifications', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_leave_types_tenant_id'), table_name='leave_types')
    op.alter_column('leave_types', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_leave_requests_tenant_id'), table_name='leave_requests')
    op.alter_column('leave_requests', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_leave_policies_tenant_id'), table_name='leave_policies')
    op.alter_column('leave_policies', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_leave_balances_tenant_id'), table_name='leave_balances')
    op.alter_column('leave_balances', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_leave_approvals_tenant_id'), table_name='leave_approvals')
    op.alter_column('leave_approvals', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.alter_column('employees', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_employee_images_tenant_id'), table_name='employee_images')
    op.alter_column('employee_images', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.alter_column('departments', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_contact_messages_tenant_id'), table_name='contact_messages')
    op.alter_column('contact_messages', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_calendar_integrations_tenant_id'), table_name='calendar_integrations')
    op.alter_column('calendar_integrations', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_approval_steps_tenant_id'), table_name='approval_steps')
    op.alter_column('approval_steps', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_approval_chains_tenant_id'), table_name='approval_chains')
    op.alter_column('approval_chains', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_accrual_logs_tenant_id'), table_name='accrual_logs')
    op.alter_column('accrual_logs', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
